<ul><li><table border="1"><tr><th>Scenario_0</th><td><table border="1"><tr><th>name</th><td>PUT request example</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046EAF90&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 221, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>steps</th><td><ul><li><table border="1"><tr><th>name</th><td>Given Set basic web application url is "http://localhost:8080/imademethink/restfulapi/account_basic/"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490929844</td></tr><tr><th>stop</th><td>1540490929844</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set basic user details as "&lt;particular&gt;" and "&lt;value&gt;" below</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>attachments</th><td><table border="1"><tr><th>name</th><th>source</th><th>type</th></tr><tr><td>.table</td><td>cb78506c-9167-479a-8672-8c799956f6f6-attachment.csv</td><td>text/csv</td></tr></table></td></tr><tr><th>start</th><td>1540490929844</td></tr><tr><th>stop</th><td>1540490929844</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Given Perform setup for PUT request</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046EAF90&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 221, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>start</th><td>1540490929844</td></tr><tr><th>stop</th><td>1540490931875</td></tr></table></li><li><table border="1"><tr><th>name</th><td>When Set PUT api endpoint as "modify_account_profile_details"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set HEADER param request content type as "application/x-www-form-urlencoded"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set HEADER param response accept type as "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set BODY form param using basic user details</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Modify BODY form param first name as "Jack" and last name as "Wilson"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Raise "PUT" HTTP request</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Then Valid HTTP response should be received</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response http code should be 200</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response HEADER content type should be "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY should not be null or empty</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY parsing for "PUT__modify_account_profile_details" should be successful</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490931891</td></tr><tr><th>stop</th><td>1540490931891</td></tr></table></li></ul></td></tr><tr><th>start</th><td>1540490929829</td></tr><tr><th>stop</th><td>1540490931891</td></tr><tr><th>uuid</th><td>f766d34f-1976-42f0-a35e-0f202fd4c2ed</td></tr><tr><th>historyId</th><td>90f7080f120ba96a896e77ee6fd70e91</td></tr><tr><th>labels</th><td><table border="1"><tr><th>name</th><th>value</th></tr><tr><td>severity</td><td>normal</td></tr><tr><td>feature</td><td>REST API testing framework using Java REST Assured or JayWay Libraries</td></tr><tr><td>framework</td><td>behave</td></tr><tr><td>language</td><td>cpython3</td></tr></table></td></tr></table></td></tr></table></li><li><table border="1"><tr><th>Scenario_1</th><td><table border="1"><tr><th>name</th><td>GET request example</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046EA7F0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 76, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>steps</th><td><ul><li><table border="1"><tr><th>name</th><td>Given Set basic web application url is "http://localhost:8080/imademethink/restfulapi/account_basic/"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490925119</td></tr><tr><th>stop</th><td>1540490925119</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set basic user details as "&lt;particular&gt;" and "&lt;value&gt;" below</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>attachments</th><td><table border="1"><tr><th>name</th><th>source</th><th>type</th></tr><tr><td>.table</td><td>2712e238-1605-4325-97ee-631ad82db1da-attachment.csv</td><td>text/csv</td></tr></table></td></tr><tr><th>start</th><td>1540490925134</td></tr><tr><th>stop</th><td>1540490925150</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Given Set GET api endpoint as "signup"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490925150</td></tr><tr><th>stop</th><td>1540490925150</td></tr></table></li><li><table border="1"><tr><th>name</th><td>When Set HEADER param request content type as "application/json"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490925150</td></tr><tr><th>stop</th><td>1540490925150</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set HEADER param response accept type as "application/json"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490925150</td></tr><tr><th>stop</th><td>1540490925150</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set Query param as "empty"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490925150</td></tr><tr><th>stop</th><td>1540490925150</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Raise "GET" HTTP request</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x046EA7F0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 76, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>start</th><td>1540490925150</td></tr><tr><th>stop</th><td>1540490927684</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Then Valid HTTP response should be received</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490927700</td></tr><tr><th>stop</th><td>1540490927700</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response http code should be 200</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490927700</td></tr><tr><th>stop</th><td>1540490927700</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response HEADER content type should be "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490927700</td></tr><tr><th>stop</th><td>1540490927700</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY should not be null or empty</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490927700</td></tr><tr><th>stop</th><td>1540490927700</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY parsing for "GET__signup" should be successful</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490927700</td></tr><tr><th>stop</th><td>1540490927700</td></tr></table></li></ul></td></tr><tr><th>start</th><td>1540490925119</td></tr><tr><th>stop</th><td>1540490927700</td></tr><tr><th>uuid</th><td>2dfb5082-4357-4c44-9340-c59eb879f996</td></tr><tr><th>historyId</th><td>7100a2c4f19733491cca4ed48252e4e9</td></tr><tr><th>labels</th><td><table border="1"><tr><th>name</th><th>value</th></tr><tr><td>severity</td><td>normal</td></tr><tr><td>feature</td><td>REST API testing framework using Java REST Assured or JayWay Libraries</td></tr><tr><td>framework</td><td>behave</td></tr><tr><td>language</td><td>cpython3</td></tr></table></td></tr></table></td></tr></table></li><li><table border="1"><tr><th>Scenario_2</th><td><table border="1"><tr><th>name</th><td>DELETE request example</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0475FFD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 164, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>steps</th><td><ul><li><table border="1"><tr><th>name</th><td>Given Set basic web application url is "http://localhost:8080/imademethink/restfulapi/account_basic/"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490931906</td></tr><tr><th>stop</th><td>1540490931906</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set basic user details as "&lt;particular&gt;" and "&lt;value&gt;" below</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>attachments</th><td><table border="1"><tr><th>name</th><th>source</th><th>type</th></tr><tr><td>.table</td><td>0273c1f5-f7a0-4a75-b897-512cc403cd2e-attachment.csv</td><td>text/csv</td></tr></table></td></tr><tr><th>start</th><td>1540490931906</td></tr><tr><th>stop</th><td>1540490931906</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Given Perform setup for DELETE request</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0475FFD0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 164, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>start</th><td>1540490931922</td></tr><tr><th>stop</th><td>1540490933964</td></tr></table></li><li><table border="1"><tr><th>name</th><td>When Set DELETE api endpoint as "signout"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set HEADER param request content type as "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set HEADER param response accept type as "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set Query param as "based on user details"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Raise "DELETE" HTTP request</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Then Valid HTTP response should be received</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response http code should be 200</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response HEADER content type should be "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY should not be null or empty</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY parsing for "DELETE__signout" should be successful</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490933969</td></tr><tr><th>stop</th><td>1540490933969</td></tr></table></li></ul></td></tr><tr><th>start</th><td>1540490931906</td></tr><tr><th>stop</th><td>1540490933969</td></tr><tr><th>uuid</th><td>b0eedf19-eb35-4e42-831c-fa20495ace50</td></tr><tr><th>historyId</th><td>0ba25ee4059fbc356322257d2c913f8c</td></tr><tr><th>labels</th><td><table border="1"><tr><th>name</th><th>value</th></tr><tr><td>severity</td><td>normal</td></tr><tr><td>feature</td><td>REST API testing framework using Java REST Assured or JayWay Libraries</td></tr><tr><td>framework</td><td>behave</td></tr><tr><td>language</td><td>cpython3</td></tr></table></td></tr></table></td></tr></table></li><li><table border="1"><tr><th>Scenario_3</th><td><table border="1"><tr><th>name</th><td>POST request example</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0475F530&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 83, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>steps</th><td><ul><li><table border="1"><tr><th>name</th><td>Given Set basic web application url is "http://localhost:8080/imademethink/restfulapi/account_basic/"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490927716</td></tr><tr><th>stop</th><td>1540490927716</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set basic user details as "&lt;particular&gt;" and "&lt;value&gt;" below</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>attachments</th><td><table border="1"><tr><th>name</th><th>source</th><th>type</th></tr><tr><td>.table</td><td>e11d7a65-2537-4e7f-a560-808aa8d47ca3-attachment.csv</td><td>text/csv</td></tr></table></td></tr><tr><th>start</th><td>1540490927716</td></tr><tr><th>stop</th><td>1540490927731</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Given Set POST api endpoint as "signup"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490927731</td></tr><tr><th>stop</th><td>1540490927731</td></tr></table></li><li><table border="1"><tr><th>name</th><td>When Set HEADER param request content type as "application/x-www-form-urlencoded"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490927731</td></tr><tr><th>stop</th><td>1540490927747</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set HEADER param response accept type as "application/json"</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490927747</td></tr><tr><th>stop</th><td>1540490927747</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Set BODY form param using basic user details</td></tr><tr><th>status</th><td>passed</td></tr><tr><th>start</th><td>1540490927747</td></tr><tr><th>stop</th><td>1540490927747</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Raise "POST" HTTP request</td></tr><tr><th>status</th><td>broken</td></tr><tr><th>statusDetails</th><td><table border="1"><tr><th>message</th><td>requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /imademethink/restfulapi/account_basic/signup (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0475F530&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</td></tr><tr><th>trace</th><td>  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\step_def_CRUD.py", line 83, in step_impl
    data=http_request_body)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\punjr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
</td></tr></table></td></tr><tr><th>start</th><td>1540490927747</td></tr><tr><th>stop</th><td>1540490929798</td></tr></table></li><li><table border="1"><tr><th>name</th><td>Then Valid HTTP response should be received</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490929813</td></tr><tr><th>stop</th><td>1540490929813</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response http code should be 201</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490929813</td></tr><tr><th>stop</th><td>1540490929813</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response HEADER content type should be "application/json"</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490929813</td></tr><tr><th>stop</th><td>1540490929813</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY should not be null or empty</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490929813</td></tr><tr><th>stop</th><td>1540490929813</td></tr></table></li><li><table border="1"><tr><th>name</th><td>And Response BODY parsing for "POST__signup" should be successful</td></tr><tr><th>status</th><td>skipped</td></tr><tr><th>start</th><td>1540490929813</td></tr><tr><th>stop</th><td>1540490929813</td></tr></table></li></ul></td></tr><tr><th>start</th><td>1540490927716</td></tr><tr><th>stop</th><td>1540490929813</td></tr><tr><th>uuid</th><td>dd088678-a8fc-4221-868d-8ee3214966e5</td></tr><tr><th>historyId</th><td>0bc8078129fb29a3fa6d9465eca516d4</td></tr><tr><th>labels</th><td><table border="1"><tr><th>name</th><th>value</th></tr><tr><td>severity</td><td>normal</td></tr><tr><td>feature</td><td>REST API testing framework using Java REST Assured or JayWay Libraries</td></tr><tr><td>framework</td><td>behave</td></tr><tr><td>language</td><td>cpython3</td></tr></table></td></tr></table></td></tr></table></li></ul>